import type { Sponsor, ZoneConfig, TrackEvent, SizeComparison } from '../types/sponsor';
import { SPONSOR_LOGOS } from './brandLogos';

export const CAMPAIGN_GOAL_MXN = 3000000; // $3,000,000 MXN
export const CONTRACT_YEARS = 2;
export const CONTRACT_DAYS = 730; // 365 * 2
export const TOTAL_AVAILABLE_CM2 = 120000; // 120,000 cm² disponibles en la carrocería (12 m²)

export const ZONES: ZoneConfig[] = [
  {
    id: 'rear_decklid',
    name: 'Tapa de Motor & Fascia Trasera (VIP)',
    shortName: 'Tapa Trasera',
    description: 'La zona trasera de máxima exposición en tomas de persecución, eventos y exhibiciones.',
    pricePerCm2: 50,
    defaultPosition: [0, 0.88, -1.70],
    defaultRotation: [-1.67, 0, 0],
    defaultScale: [0.85, 0.25, 1],
    cameraPreset: {
      position: [0, 1.6, -3.2],
      target: [0, 0.7, -1.4],
    },
    highlightColor: '#fdd835',
    badgeText: 'MÁXIMO IMPACTO',
  },
  {
    id: 'hood_central',
    name: 'Cofre Aerodinámico Central',
    shortName: 'Cofre Central',
    description: 'Impacto frontal directo. Visible en todas las tomas frontales, videos y exhibiciones.',
    pricePerCm2: 45,
    defaultPosition: [0, 0.72, 1.25],
    defaultRotation: [-1.22, 0, 0],
    defaultScale: [0.70, 0.38, 1],
    cameraPreset: {
      position: [0, 1.6, 3.0],
      target: [0, 0.6, 1.0],
    },
    highlightColor: '#e00000',
    badgeText: 'FRONTAL ESTRELLA',
  },
  {
    id: 'premium_door',
    name: 'Puertas Laterales',
    shortName: 'Puertas Laterales',
    description: 'Gran formato lateral. El espacio clásico de los autos GT de competición para patrocinios principales.',
    pricePerCm2: 35,
    defaultPosition: [0.93, 0.65, 0.05],
    defaultRotation: [0, 1.57, 0],
    defaultScale: [0.75, 0.38, 1],
    cameraPreset: {
      position: [3.4, 1.0, 0.0],
      target: [0, 0.6, 0.0],
    },
    highlightColor: '#0070bb',
    badgeText: 'GRAN FORMATO',
  },
  {
    id: 'body_standard',
    name: 'Salpicaderas, Costados & Defensas',
    shortName: 'Salpicaderas',
    description: 'Salpicaderas delanteras y traseras con visibilidad dinámica 360° en curvas (Tarifa Base).',
    pricePerCm2: 25,
    defaultPosition: [-0.88, 0.60, 1.15],
    defaultRotation: [-0.15, -1.45, 0],
    defaultScale: [0.50, 0.25, 1],
    cameraPreset: {
      position: [-2.6, 1.1, 1.8],
      target: [-0.4, 0.6, 0.6],
    },
    highlightColor: '#10b981',
    badgeText: 'TARIFA BASE $25',
  },
];

export const SIZE_COMPARISONS: SizeComparison[] = [
  {
    name: 'Micro Sticker (Tarjeta)',
    dimensions: '8.5 x 5.5 cm',
    cm2: 50,
    objectComparison: 'Tamaño Tarjeta de Crédito',
    dailyCostMxn: (50 * 25) / CONTRACT_DAYS,
    totalMxn: 1250,
    iconName: 'CreditCard',
  },
  {
    name: 'Badge Pro (Smartphone)',
    dimensions: '10 x 15 cm',
    cm2: 150,
    objectComparison: 'Tamaño iPhone Pro Max',
    dailyCostMxn: (150 * 35) / CONTRACT_DAYS,
    totalMxn: 5250,
    iconName: 'Smartphone',
  },
  {
    name: 'Medium Banner (Tablet)',
    dimensions: '20 x 25 cm',
    cm2: 500,
    objectComparison: 'Tamaño iPad / Revista',
    dailyCostMxn: (500 * 35) / CONTRACT_DAYS,
    totalMxn: 17500,
    iconName: 'Tablet',
  },
  {
    name: 'Mega Logo (Laptop)',
    dimensions: '35 x 30 cm',
    cm2: 1050,
    objectComparison: 'Tamaño Laptop 15" / Puerta',
    dailyCostMxn: (1050 * 45) / CONTRACT_DAYS,
    totalMxn: 47250,
    iconName: 'Monitor',
  },
  {
    name: 'Title Sponsor (Trasera Completa)',
    dimensions: '140 x 25 cm',
    cm2: 3500,
    objectComparison: 'Envergadura total trasera del Porsche 911',
    dailyCostMxn: (3500 * 50) / CONTRACT_DAYS,
    totalMxn: 175000,
    iconName: 'Trophy',
  },
];

export const TRACK_EVENTS_ROADMAP: TrackEvent[] = [
  {
    id: 'track-1',
    title: 'Gran Lanzamiento & Vinilado Oficial en Vivo',
    location: 'Porsche Center CDMX / Santa Fe',
    trackName: 'Exhibición Inaugural',
    date: 'Día 1 de Entrega',
    yearSpan: 'Año 1 - 2026',
    estimatedReach: '500,000+ Vistas digitales & invitados VIP',
    type: 'Exhibición VIP',
    description: 'Sesión de rotulación en vivo con vinil automotriz de alta resistencia de todos los patrocinadores, unboxing oficial del 911 (992) y cobertura mediática.',
  },
  {
    id: 'track-2',
    title: 'Car Meets & Expos de Superautos Exclusivos',
    location: 'Valle de Bravo, Cancún, Zapopan, San Pedro Garza García, CDMX',
    trackName: 'Country Clubs, Plazas de Lujo & Caravanas',
    date: 'Mensual durante 2 años',
    yearSpan: '24 Car Meets en 2 años',
    estimatedReach: 'Comunidad de alto poder adquisitivo, directores y entusiastas',
    type: 'Car Meet & Expo',
    description: 'Presencia continua en las reuniones de superdeportivos más exclusivas de México con material fotográfico y video profesional para los patrocinadores.',
  },
  {
    id: 'track-3',
    title: 'Track Days & Gira en Autódromos (F1)',
    location: 'CDMX (Hermanos Rodríguez), Monterrey, San Luis Potosí',
    trackName: 'Autódromo Hermanos Rodríguez, Tangamanga & Monterrey',
    date: 'Temporadas de Pista',
    yearSpan: '2 Años de Gira Oficial',
    estimatedReach: '60,000+ Aficionados presenciales en pits y gradas + Cobertura nacional',
    type: 'Track Day Time Attack',
    description: 'Vueltas rápidas en circuitos profesionales. Los logos en cofre, puertas, techo y parte trasera serán capturados en cámaras de alta velocidad y tomas on-board.',
  },
];

// Complete 38-Sponsor Dataset: 100% Sold Out, zero overlapping, perfectly positioned across all panels
export const SOLD_OUT_SPONSORS: Sponsor[] = [
  // --- COFRE CENTRAL (HOOD) ---
  {
    id: 'sp-hood-1',
    brandName: 'Red Bull Racing México',
    sponsorName: 'Red Bull Energy Drink',
    slogan: 'Gives You Wings · Patrocinador Principal de Pista',
    logoUrl: SPONSOR_LOGOS['sp-hood-1'] || '',
    targetUrl: 'https://redbull.com',
    email: 'racing@redbull.com',
    tier: 'hood_central',
    zoneName: 'Cofre Central Frontal',
    widthCm: 32,
    heightCm: 18,
    areaCm2: 576,
    pricePerCm2: 45,
    totalPriceMxn: 180000,
    position3D: [0, 0.72, 1.25],
    rotation3D: [-1.22, 0, 0],
    scale3D: [1.14, 0.64, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-01',
    expiryDate: '2028-08-01',
    viewsCount: 14820,
    clicksCount: 1240,
    certificateId: 'P992-HOOD-789012',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 3,
  },
  {
    id: 'sp-hood-2',
    brandName: 'Shopify LATAM',
    sponsorName: 'Shopify E-Commerce',
    slogan: 'Empowering Next-Gen Creators & Brands',
    logoUrl: SPONSOR_LOGOS['sp-hood-2'] || '',
    targetUrl: 'https://shopify.com',
    email: 'latam@shopify.com',
    tier: 'hood_central',
    zoneName: 'Cofre Superior Central',
    widthCm: 26,
    heightCm: 14,
    areaCm2: 364,
    pricePerCm2: 45,
    totalPriceMxn: 120000,
    position3D: [0, 0.78, 0.90],
    rotation3D: [-1.15, 0, 0],
    scale3D: [0.92, 0.50, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-02',
    expiryDate: '2028-08-02',
    viewsCount: 9450,
    clicksCount: 820,
    certificateId: 'P992-HOOD-456123',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 3,
  },
  {
    id: 'sp-hood-3',
    brandName: 'Mercado Libre Tech',
    sponsorName: 'Mercado Libre México',
    slogan: 'Lo mejor está llegando · Envíos Full',
    logoUrl: SPONSOR_LOGOS['sp-hood-3'] || '',
    targetUrl: 'https://mercadolibre.com.mx',
    email: 'patrocinios@mercadolibre.com.mx',
    tier: 'hood_central',
    zoneName: 'Cofre Inferior Frontal',
    widthCm: 28,
    heightCm: 12,
    areaCm2: 336,
    pricePerCm2: 45,
    totalPriceMxn: 110000,
    position3D: [0, 0.66, 1.58],
    rotation3D: [-1.30, 0, 0],
    scale3D: [1.0, 0.42, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-03',
    expiryDate: '2028-08-03',
    viewsCount: 8900,
    clicksCount: 710,
    certificateId: 'P992-HOOD-654987',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 3,
  },
  {
    id: 'sp-hood-4',
    brandName: 'Kavak México',
    sponsorName: 'Kavak Supercars',
    slogan: 'Compra y Vende Autos Certificados',
    logoUrl: SPONSOR_LOGOS['sp-hood-4'] || '',
    targetUrl: 'https://kavak.com/mx',
    email: 'vip@kavak.com',
    tier: 'hood_central',
    zoneName: 'Cofre Superior Izquierdo',
    widthCm: 24,
    heightCm: 14,
    areaCm2: 336,
    pricePerCm2: 45,
    totalPriceMxn: 95000,
    position3D: [-0.40, 0.75, 1.05],
    rotation3D: [-1.18, 0, 0],
    scale3D: [0.85, 0.50, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-04',
    expiryDate: '2028-08-04',
    viewsCount: 7200,
    clicksCount: 590,
    certificateId: 'P992-HOOD-321789',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 3,
  },
  {
    id: 'sp-hood-5',
    brandName: 'Bitso Crypto',
    sponsorName: 'Bitso Exchange',
    slogan: 'Haciendo que las finanzas sean sin fronteras',
    logoUrl: SPONSOR_LOGOS['sp-hood-5'] || '',
    targetUrl: 'https://bitso.com',
    email: 'contacto@bitso.com',
    tier: 'hood_central',
    zoneName: 'Cofre Superior Derecho',
    widthCm: 24,
    heightCm: 14,
    areaCm2: 336,
    pricePerCm2: 45,
    totalPriceMxn: 95000,
    position3D: [0.40, 0.75, 1.05],
    rotation3D: [-1.18, 0, 0],
    scale3D: [0.85, 0.50, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-05',
    expiryDate: '2028-08-05',
    viewsCount: 6800,
    clicksCount: 510,
    certificateId: 'P992-HOOD-159753',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 3,
  },
  {
    id: 'sp-hood-6',
    brandName: 'Nu México',
    sponsorName: 'Nu Bank',
    slogan: 'El futuro morado del dinero · Sin comisiones',
    logoUrl: SPONSOR_LOGOS['sp-hood-6'] || '',
    targetUrl: 'https://nu.com.mx',
    email: 'hola@nu.com.mx',
    tier: 'hood_central',
    zoneName: 'Cofre Frontal Izquierdo',
    widthCm: 22,
    heightCm: 13,
    areaCm2: 286,
    pricePerCm2: 45,
    totalPriceMxn: 85000,
    position3D: [-0.36, 0.69, 1.42],
    rotation3D: [-1.25, 0, 0],
    scale3D: [0.78, 0.46, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-06',
    expiryDate: '2028-08-06',
    viewsCount: 6100,
    clicksCount: 480,
    certificateId: 'P992-HOOD-951357',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 3,
  },
  {
    id: 'sp-hood-7',
    brandName: 'Clip Pagos',
    sponsorName: 'Clip Terminales México',
    slogan: 'Acepta todas las tarjetas al instante',
    logoUrl: SPONSOR_LOGOS['sp-hood-7'] || '',
    targetUrl: 'https://clip.mx',
    email: 'marketing@clip.mx',
    tier: 'hood_central',
    zoneName: 'Cofre Frontal Derecho',
    widthCm: 22,
    heightCm: 13,
    areaCm2: 286,
    pricePerCm2: 45,
    totalPriceMxn: 85000,
    position3D: [0.36, 0.69, 1.42],
    rotation3D: [-1.25, 0, 0],
    scale3D: [0.78, 0.46, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-07',
    expiryDate: '2028-08-07',
    viewsCount: 5900,
    clicksCount: 430,
    certificateId: 'P992-HOOD-852963',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 3,
  },

  // --- TECHO PANORÁMICO (ROOF) ---
  {
    id: 'sp-roof-1',
    brandName: 'Spotify México',
    sponsorName: 'Spotify Soundtracks',
    slogan: 'Música para manejar a 300 km/h',
    logoUrl: SPONSOR_LOGOS['sp-roof-1'] || '',
    targetUrl: 'https://spotify.com',
    email: 'ads@spotify.com',
    tier: 'body_standard',
    zoneName: 'Techo Central Panorámico',
    widthCm: 38,
    heightCm: 22,
    areaCm2: 836,
    pricePerCm2: 30,
    totalPriceMxn: 210000,
    position3D: [0, 1.34, -0.10],
    rotation3D: [-1.57, 0, 0],
    scale3D: [1.35, 0.78, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-08',
    expiryDate: '2028-08-08',
    viewsCount: 16500,
    clicksCount: 1420,
    certificateId: 'P992-ROOF-741852',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
  },
  {
    id: 'sp-roof-2',
    brandName: 'Monster Energy',
    sponsorName: 'Monster Energy Drinks',
    slogan: 'Unleash The Beast · Motorsports Edition',
    logoUrl: SPONSOR_LOGOS['sp-roof-2'] || '',
    targetUrl: 'https://monsterenergy.com',
    email: 'motorsports@monsterenergy.com',
    tier: 'body_standard',
    zoneName: 'Techo Delantero',
    widthCm: 28,
    heightCm: 16,
    areaCm2: 448,
    pricePerCm2: 30,
    totalPriceMxn: 120000,
    position3D: [0, 1.33, 0.28],
    rotation3D: [-1.50, 0, 0],
    scale3D: [1.0, 0.57, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-09',
    expiryDate: '2028-08-09',
    viewsCount: 11200,
    clicksCount: 940,
    certificateId: 'P992-ROOF-963852',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
  },
  {
    id: 'sp-roof-3',
    brandName: 'Discord Gaming',
    sponsorName: 'Discord Inc.',
    slogan: 'Your Place to Talk, Play & Hang Out',
    logoUrl: SPONSOR_LOGOS['sp-roof-3'] || '',
    targetUrl: 'https://discord.com',
    email: 'partners@discord.com',
    tier: 'body_standard',
    zoneName: 'Techo Posterior',
    widthCm: 30,
    heightCm: 15,
    areaCm2: 450,
    pricePerCm2: 30,
    totalPriceMxn: 115000,
    position3D: [0, 1.32, -0.48],
    rotation3D: [-1.65, 0, 0],
    scale3D: [1.07, 0.53, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-10',
    expiryDate: '2028-08-10',
    viewsCount: 10400,
    clicksCount: 880,
    certificateId: 'P992-ROOF-147258',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
  },
  {
    id: 'sp-roof-4',
    brandName: 'GitHub Dev',
    sponsorName: 'GitHub Inc.',
    slogan: 'Where the world builds software',
    logoUrl: SPONSOR_LOGOS['sp-roof-4'] || '',
    targetUrl: 'https://github.com',
    email: 'devs@github.com',
    tier: 'body_standard',
    zoneName: 'Techo Lateral Izquierdo',
    widthCm: 24,
    heightCm: 14,
    areaCm2: 336,
    pricePerCm2: 30,
    totalPriceMxn: 80000,
    position3D: [-0.36, 1.33, -0.10],
    rotation3D: [-1.57, 0, 0],
    scale3D: [0.85, 0.50, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-11',
    expiryDate: '2028-08-11',
    viewsCount: 7800,
    clicksCount: 650,
    certificateId: 'P992-ROOF-369258',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
  },
  {
    id: 'sp-roof-5',
    brandName: 'Figma Design',
    sponsorName: 'Figma Software',
    slogan: 'Nothing great is made alone',
    logoUrl: SPONSOR_LOGOS['sp-roof-5'] || '',
    targetUrl: 'https://figma.com',
    email: 'design@figma.com',
    tier: 'body_standard',
    zoneName: 'Techo Lateral Derecho',
    widthCm: 24,
    heightCm: 14,
    areaCm2: 336,
    pricePerCm2: 30,
    totalPriceMxn: 80000,
    position3D: [0.36, 1.33, -0.10],
    rotation3D: [-1.57, 0, 0],
    scale3D: [0.85, 0.50, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-12',
    expiryDate: '2028-08-12',
    viewsCount: 7500,
    clicksCount: 620,
    certificateId: 'P992-ROOF-258147',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
  },
  {
    id: 'sp-roof-6',
    brandName: 'Stripe Payments',
    sponsorName: 'Stripe Payments LATAM',
    slogan: 'Financial infrastructure for the internet',
    logoUrl: SPONSOR_LOGOS['sp-roof-6'] || '',
    targetUrl: 'https://stripe.com',
    email: 'latam@stripe.com',
    tier: 'body_standard',
    zoneName: 'Techo Frontal Izquierdo',
    widthCm: 22,
    heightCm: 13,
    areaCm2: 286,
    pricePerCm2: 30,
    totalPriceMxn: 70000,
    position3D: [-0.34, 1.32, 0.25],
    rotation3D: [-1.50, 0, 0],
    scale3D: [0.78, 0.46, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-13',
    expiryDate: '2028-08-13',
    viewsCount: 6400,
    clicksCount: 510,
    certificateId: 'P992-ROOF-753951',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
  },
  {
    id: 'sp-roof-7',
    brandName: 'Notion Workspace',
    sponsorName: 'Notion Labs',
    slogan: 'The all-in-one workspace for your ideas',
    logoUrl: SPONSOR_LOGOS['sp-roof-7'] || '',
    targetUrl: 'https://notion.so',
    email: 'team@makenotion.com',
    tier: 'body_standard',
    zoneName: 'Techo Frontal Derecho',
    widthCm: 22,
    heightCm: 13,
    areaCm2: 286,
    pricePerCm2: 30,
    totalPriceMxn: 70000,
    position3D: [0.34, 1.32, 0.25],
    rotation3D: [-1.50, 0, 0],
    scale3D: [0.78, 0.46, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-14',
    expiryDate: '2028-08-14',
    viewsCount: 6200,
    clicksCount: 490,
    certificateId: 'P992-ROOF-852147',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
  },

  // --- PUERTA IZQUIERDA & SALPICADERAS IZQUIERDAS (LEFT SIDE) ---
  {
    id: 'sp-door-l1',
    brandName: 'TAG Heuer Chrono',
    sponsorName: 'TAG Heuer Swiss Watches',
    slogan: 'Don’t Crack Under Pressure · Official Chrono',
    logoUrl: SPONSOR_LOGOS['sp-door-l1'] || '',
    targetUrl: 'https://tagheuer.com',
    email: 'motorsport@tagheuer.com',
    tier: 'premium_door',
    zoneName: 'Puerta Lateral Izquierda (Centro)',
    widthCm: 42,
    heightCm: 22,
    areaCm2: 924,
    pricePerCm2: 35,
    totalPriceMxn: 200000,
    position3D: [-0.93, 0.65, 0.05],
    rotation3D: [0, -1.57, 0],
    scale3D: [1.50, 0.78, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-15',
    expiryDate: '2028-08-15',
    viewsCount: 18200,
    clicksCount: 1650,
    certificateId: 'P992-DOOR-369147',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 3,
  },
  {
    id: 'sp-door-l2',
    brandName: 'Michelin Motorsport',
    sponsorName: 'Michelin Tyres',
    slogan: 'A better way forward · Pilot Sport Cup 2',
    logoUrl: SPONSOR_LOGOS['sp-door-l2'] || '',
    targetUrl: 'https://michelin.com.mx',
    email: 'porsche@michelin.com',
    tier: 'premium_door',
    zoneName: 'Puerta Izquierda Frontal',
    widthCm: 26,
    heightCm: 13,
    areaCm2: 338,
    pricePerCm2: 35,
    totalPriceMxn: 85000,
    position3D: [-0.92, 0.66, 0.48],
    rotation3D: [0, -1.57, 0],
    scale3D: [0.92, 0.46, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-16',
    expiryDate: '2028-08-16',
    viewsCount: 8900,
    clicksCount: 720,
    certificateId: 'P992-DOOR-147369',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
  },
  {
    id: 'sp-door-l3',
    brandName: 'Mobil 1 Racing Oil',
    sponsorName: 'Mobil 1 Synthetic Oil',
    slogan: 'Official Factory Fill of Porsche Motorsport',
    logoUrl: SPONSOR_LOGOS['sp-door-l3'] || '',
    targetUrl: 'https://mobil1.com',
    email: 'racing@mobil1.com',
    tier: 'premium_door',
    zoneName: 'Puerta Izquierda Posterior',
    widthCm: 26,
    heightCm: 13,
    areaCm2: 338,
    pricePerCm2: 35,
    totalPriceMxn: 85000,
    position3D: [-0.92, 0.65, -0.38],
    rotation3D: [0, -1.57, 0],
    scale3D: [0.92, 0.46, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-17',
    expiryDate: '2028-08-17',
    viewsCount: 8600,
    clicksCount: 690,
    certificateId: 'P992-DOOR-258369',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
  },
  {
    id: 'sp-door-l4',
    brandName: 'Bose Audio Systems',
    sponsorName: 'Bose Sound',
    slogan: 'Sound is Power · Porsche Surround Sound',
    logoUrl: SPONSOR_LOGOS['sp-door-l4'] || '',
    targetUrl: 'https://bose.com',
    email: 'auto@bose.com',
    tier: 'premium_door',
    zoneName: 'Puerta Izquierda Superior',
    widthCm: 22,
    heightCm: 11,
    areaCm2: 242,
    pricePerCm2: 35,
    totalPriceMxn: 60000,
    position3D: [-0.90, 0.78, 0.05],
    rotation3D: [0, -1.57, 0],
    scale3D: [0.78, 0.39, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-18',
    expiryDate: '2028-08-18',
    viewsCount: 5800,
    clicksCount: 420,
    certificateId: 'P992-DOOR-789123',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
  },
  {
    id: 'sp-door-l5',
    brandName: 'Brembo Brakes',
    sponsorName: 'Brembo Racing',
    slogan: 'Turning Energy into Pure Stopping Power',
    logoUrl: SPONSOR_LOGOS['sp-door-l5'] || '',
    targetUrl: 'https://brembo.com',
    email: 'racing@brembo.it',
    tier: 'premium_door',
    zoneName: 'Faldón Lateral Izquierdo',
    widthCm: 24,
    heightCm: 11,
    areaCm2: 264,
    pricePerCm2: 35,
    totalPriceMxn: 60000,
    position3D: [-0.91, 0.52, 0.05],
    rotation3D: [0, -1.57, 0],
    scale3D: [0.85, 0.39, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-19',
    expiryDate: '2028-08-19',
    viewsCount: 5400,
    clicksCount: 390,
    certificateId: 'P992-DOOR-456789',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
  },
  {
    id: 'sp-door-l6',
    brandName: 'BBS Motorsport',
    sponsorName: 'BBS Wheels',
    slogan: 'Legendary Forged Performance Wheels',
    logoUrl: SPONSOR_LOGOS['sp-door-l6'] || '',
    targetUrl: 'https://bbs.com',
    email: 'info@bbs.com',
    tier: 'body_standard',
    zoneName: 'Salpicadera Trasera Izquierda',
    widthCm: 24,
    heightCm: 13,
    areaCm2: 312,
    pricePerCm2: 25,
    totalPriceMxn: 55000,
    position3D: [-0.96, 0.72, -0.85],
    rotation3D: [0, -1.57, 0],
    scale3D: [0.85, 0.46, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-20',
    expiryDate: '2028-08-20',
    viewsCount: 4900,
    clicksCount: 340,
    certificateId: 'P992-BODY-123456',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
  },
  {
    id: 'sp-door-l7',
    brandName: 'Recaro Racing Seats',
    sponsorName: 'Recaro Automotive',
    slogan: 'First in Seat Safety & GT Motorsport Comfort',
    logoUrl: SPONSOR_LOGOS['sp-door-l7'] || '',
    targetUrl: 'https://recaro-automotive.com',
    email: 'info@recaro.com',
    tier: 'body_standard',
    zoneName: 'Salpicadera Delantera Izquierda',
    widthCm: 22,
    heightCm: 12,
    areaCm2: 264,
    pricePerCm2: 25,
    totalPriceMxn: 50000,
    position3D: [-0.90, 0.68, 0.95],
    rotation3D: [-0.10, -1.45, 0],
    scale3D: [0.78, 0.42, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-21',
    expiryDate: '2028-08-21',
    viewsCount: 4600,
    clicksCount: 310,
    certificateId: 'P992-BODY-654321',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
  },

  // --- PUERTA DERECHA & SALPICADERAS DERECHAS (RIGHT SIDE) ---
  {
    id: 'sp-door-r1',
    brandName: 'Rolex Cosmograph',
    sponsorName: 'Rolex Swiss Horology',
    slogan: 'The Official Timepiece of Motor Racing Excellence',
    logoUrl: SPONSOR_LOGOS['sp-door-r1'] || '',
    targetUrl: 'https://rolex.com',
    email: 'contact@rolex.com',
    tier: 'premium_door',
    zoneName: 'Puerta Lateral Derecha (Centro)',
    widthCm: 42,
    heightCm: 22,
    areaCm2: 924,
    pricePerCm2: 35,
    totalPriceMxn: 200000,
    position3D: [0.93, 0.65, 0.05],
    rotation3D: [0, 1.57, 0],
    scale3D: [1.50, 0.78, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-22',
    expiryDate: '2028-08-22',
    viewsCount: 17900,
    clicksCount: 1580,
    certificateId: 'P992-DOOR-987654',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 3,
  },
  {
    id: 'sp-door-r2',
    brandName: 'Pirelli P-Zero',
    sponsorName: 'Pirelli Motorsport',
    slogan: 'Power is Nothing Without Control',
    logoUrl: SPONSOR_LOGOS['sp-door-r2'] || '',
    targetUrl: 'https://pirelli.com',
    email: 'motorsport@pirelli.com',
    tier: 'premium_door',
    zoneName: 'Puerta Derecha Frontal',
    widthCm: 26,
    heightCm: 13,
    areaCm2: 338,
    pricePerCm2: 35,
    totalPriceMxn: 85000,
    position3D: [0.92, 0.66, 0.48],
    rotation3D: [0, 1.57, 0],
    scale3D: [0.92, 0.46, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-23',
    expiryDate: '2028-08-23',
    viewsCount: 8400,
    clicksCount: 680,
    certificateId: 'P992-DOOR-321654',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
  },
  {
    id: 'sp-door-r3',
    brandName: 'Castrol Edge Supercar',
    sponsorName: 'Castrol Global',
    slogan: 'Titanium Strong For Maximum GT Engine Power',
    logoUrl: SPONSOR_LOGOS['sp-door-r3'] || '',
    targetUrl: 'https://castrol.com',
    email: 'edge@castrol.com',
    tier: 'premium_door',
    zoneName: 'Puerta Derecha Posterior',
    widthCm: 26,
    heightCm: 13,
    areaCm2: 338,
    pricePerCm2: 35,
    totalPriceMxn: 85000,
    position3D: [0.92, 0.65, -0.38],
    rotation3D: [0, 1.57, 0],
    scale3D: [0.92, 0.46, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-24',
    expiryDate: '2028-08-24',
    viewsCount: 8200,
    clicksCount: 660,
    certificateId: 'P992-DOOR-654789',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
  },
  {
    id: 'sp-door-r4',
    brandName: 'Oakley Motorsports',
    sponsorName: 'Oakley Sunglasses',
    slogan: 'Precision Optics for High Velocity Drivers',
    logoUrl: SPONSOR_LOGOS['sp-door-r4'] || '',
    targetUrl: 'https://oakley.com',
    email: 'sports@oakley.com',
    tier: 'premium_door',
    zoneName: 'Puerta Derecha Superior',
    widthCm: 22,
    heightCm: 11,
    areaCm2: 242,
    pricePerCm2: 35,
    totalPriceMxn: 60000,
    position3D: [0.90, 0.78, 0.05],
    rotation3D: [0, 1.57, 0],
    scale3D: [0.78, 0.39, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-25',
    expiryDate: '2028-08-25',
    viewsCount: 5600,
    clicksCount: 410,
    certificateId: 'P992-DOOR-159357',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
  },
  {
    id: 'sp-door-r5',
    brandName: 'Akrapovič Titanium',
    sponsorName: 'Akrapovič Exhaust Systems',
    slogan: 'Uncompromising GT Sound & Extreme Lightweight',
    logoUrl: SPONSOR_LOGOS['sp-door-r5'] || '',
    targetUrl: 'https://akrapovic.com',
    email: 'info@akrapovic.com',
    tier: 'premium_door',
    zoneName: 'Faldón Lateral Derecho',
    widthCm: 24,
    heightCm: 11,
    areaCm2: 264,
    pricePerCm2: 35,
    totalPriceMxn: 60000,
    position3D: [0.91, 0.52, 0.05],
    rotation3D: [0, 1.57, 0],
    scale3D: [0.85, 0.39, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-26',
    expiryDate: '2028-08-26',
    viewsCount: 5200,
    clicksCount: 380,
    certificateId: 'P992-DOOR-357159',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
  },
  {
    id: 'sp-door-r6',
    brandName: 'HRE Wheels',
    sponsorName: 'HRE Performance Wheels',
    slogan: 'Custom Forged Luxury & Motorsport Wheels',
    logoUrl: SPONSOR_LOGOS['sp-door-r6'] || '',
    targetUrl: 'https://hrewheels.com',
    email: 'sales@hrewheels.com',
    tier: 'body_standard',
    zoneName: 'Salpicadera Trasera Derecha',
    widthCm: 24,
    heightCm: 13,
    areaCm2: 312,
    pricePerCm2: 25,
    totalPriceMxn: 55000,
    position3D: [0.96, 0.72, -0.85],
    rotation3D: [0, 1.57, 0],
    scale3D: [0.85, 0.46, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-27',
    expiryDate: '2028-08-27',
    viewsCount: 4700,
    clicksCount: 320,
    certificateId: 'P992-BODY-753159',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
  },
  {
    id: 'sp-door-r7',
    brandName: 'Sparco Racing Gear',
    sponsorName: 'Sparco Official',
    slogan: 'Driver Safety & Professional Racing Equipment',
    logoUrl: SPONSOR_LOGOS['sp-door-r7'] || '',
    targetUrl: 'https://sparco-official.com',
    email: 'info@sparco.it',
    tier: 'body_standard',
    zoneName: 'Salpicadera Delantera Derecha',
    widthCm: 22,
    heightCm: 12,
    areaCm2: 264,
    pricePerCm2: 25,
    totalPriceMxn: 50000,
    position3D: [0.90, 0.68, 0.95],
    rotation3D: [-0.10, 1.45, 0],
    scale3D: [0.78, 0.42, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-28',
    expiryDate: '2028-08-28',
    viewsCount: 4400,
    clicksCount: 300,
    certificateId: 'P992-BODY-951753',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
  },

  // --- TAPA TRASERA & FASCIA TRASERA (REAR DECKLID & BUMPER) ---
  {
    id: 'sp-rear-1',
    brandName: 'Porsche Club México (VIP)',
    sponsorName: 'Porsche Club México A.C.',
    slogan: 'Pasión por la marca de Stuttgart · Title Partner',
    logoUrl: SPONSOR_LOGOS['sp-rear-1'] || '',
    targetUrl: 'https://porscheclubmexico.com',
    email: 'presidencia@porscheclubmexico.com',
    tier: 'rear_decklid',
    zoneName: 'Tapa de Motor Central (VIP)',
    widthCm: 46,
    heightCm: 18,
    areaCm2: 828,
    pricePerCm2: 50,
    totalPriceMxn: 250000,
    position3D: [0, 0.88, -1.70],
    rotation3D: [-1.67, 0, 0],
    scale3D: [1.64, 0.64, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-28',
    expiryDate: '2028-08-28',
    viewsCount: 22400,
    clicksCount: 2100,
    certificateId: 'P992-VIP-100001',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 4,
  },
  {
    id: 'sp-rear-2',
    brandName: 'Nürburgring Official',
    sponsorName: 'Nürburgring 1927 GmbH',
    slogan: 'The Green Hell · 20.8 km of Pure Adrenaline',
    logoUrl: SPONSOR_LOGOS['sp-rear-2'] || '',
    targetUrl: 'https://nuerburgring.de',
    email: 'motorsport@nuerburgring.de',
    tier: 'rear_decklid',
    zoneName: 'Alerón Superior Trasero',
    widthCm: 32,
    heightCm: 14,
    areaCm2: 448,
    pricePerCm2: 50,
    totalPriceMxn: 100000,
    position3D: [0, 1.05, -1.25],
    rotation3D: [-1.75, 0, 0],
    scale3D: [1.14, 0.50, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-28',
    expiryDate: '2028-08-28',
    viewsCount: 14500,
    clicksCount: 1320,
    certificateId: 'P992-VIP-200002',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 4,
  },
  {
    id: 'sp-rear-3',
    brandName: 'GoPro Hero Cameras',
    sponsorName: 'GoPro Action Cameras',
    slogan: 'Be a HERO · High Speed On-Board 4K Track Video',
    logoUrl: SPONSOR_LOGOS['sp-rear-3'] || '',
    targetUrl: 'https://gopro.com',
    email: 'partners@gopro.com',
    tier: 'body_standard',
    zoneName: 'Defensa Trasera Central',
    widthCm: 28,
    heightCm: 12,
    areaCm2: 336,
    pricePerCm2: 25,
    totalPriceMxn: 65000,
    position3D: [0, 0.65, -1.98],
    rotation3D: [0, 3.14, 0],
    scale3D: [1.0, 0.42, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-28',
    expiryDate: '2028-08-28',
    viewsCount: 7100,
    clicksCount: 580,
    certificateId: 'P992-BODY-300003',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
  },
  {
    id: 'sp-rear-4',
    brandName: 'Bilstein Suspension',
    sponsorName: 'Bilstein Shock Absorbers',
    slogan: 'Drive the Legend · Nordschleife Tuned Damper Tech',
    logoUrl: SPONSOR_LOGOS['sp-rear-4'] || '',
    targetUrl: 'https://bilstein.com',
    email: 'motorsport@bilstein.de',
    tier: 'rear_decklid',
    zoneName: 'Tapa Trasera Izquierda',
    widthCm: 22,
    heightCm: 12,
    areaCm2: 264,
    pricePerCm2: 50,
    totalPriceMxn: 65000,
    position3D: [-0.45, 0.86, -1.72],
    rotation3D: [-1.67, 0, 0],
    scale3D: [0.78, 0.42, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-28',
    expiryDate: '2028-08-28',
    viewsCount: 6300,
    clicksCount: 490,
    certificateId: 'P992-VIP-400004',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 4,
  },
  {
    id: 'sp-rear-5',
    brandName: 'KW Automotive',
    sponsorName: 'KW suspensions',
    slogan: 'The Perfect Suspension for Every Demand',
    logoUrl: SPONSOR_LOGOS['sp-rear-5'] || '',
    targetUrl: 'https://kwsuspensions.com',
    email: 'info@kwsuspensions.de',
    tier: 'rear_decklid',
    zoneName: 'Tapa Trasera Derecha',
    widthCm: 22,
    heightCm: 12,
    areaCm2: 264,
    pricePerCm2: 50,
    totalPriceMxn: 65000,
    position3D: [0.45, 0.86, -1.72],
    rotation3D: [-1.67, 0, 0],
    scale3D: [0.78, 0.42, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-28',
    expiryDate: '2028-08-28',
    viewsCount: 6200,
    clicksCount: 480,
    certificateId: 'P992-VIP-500005',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 4,
  },
  {
    id: 'sp-rear-6',
    brandName: 'Borla Performance',
    sponsorName: 'Borla Exhaust',
    slogan: 'Million Mile Warranty High Flow GT Exhausts',
    logoUrl: SPONSOR_LOGOS['sp-rear-6'] || '',
    targetUrl: 'https://borla.com',
    email: 'sales@borla.com',
    tier: 'body_standard',
    zoneName: 'Defensa Trasera Izquierda',
    widthCm: 22,
    heightCm: 11,
    areaCm2: 242,
    pricePerCm2: 25,
    totalPriceMxn: 45000,
    position3D: [-0.58, 0.65, -1.92],
    rotation3D: [0, 3.14, 0],
    scale3D: [0.78, 0.39, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-28',
    expiryDate: '2028-08-28',
    viewsCount: 4300,
    clicksCount: 290,
    certificateId: 'P992-BODY-600006',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
  },
  {
    id: 'sp-rear-7',
    brandName: 'Remus Sportexhaust',
    sponsorName: 'Remus Austria',
    slogan: 'Sound, Design and High Performance',
    logoUrl: SPONSOR_LOGOS['sp-rear-7'] || '',
    targetUrl: 'https://remus.eu',
    email: 'office@remus.at',
    tier: 'body_standard',
    zoneName: 'Defensa Trasera Derecha',
    widthCm: 22,
    heightCm: 11,
    areaCm2: 242,
    pricePerCm2: 25,
    totalPriceMxn: 45000,
    position3D: [0.58, 0.65, -1.92],
    rotation3D: [0, 3.14, 0],
    scale3D: [0.78, 0.39, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-28',
    expiryDate: '2028-08-28',
    viewsCount: 4200,
    clicksCount: 280,
    certificateId: 'P992-BODY-700007',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
  },

  // --- DEFENSAS FRONTALES (FRONT BUMPERS) ---
  {
    id: 'sp-front-1',
    brandName: 'Bell Racing Helmets',
    sponsorName: 'Bell Helmets Worldwide',
    slogan: 'World Champions Choice in FIA Auto Racing',
    logoUrl: SPONSOR_LOGOS['sp-front-1'] || '',
    targetUrl: 'https://bellracing.com',
    email: 'f1@bellracing.com',
    tier: 'body_standard',
    zoneName: 'Defensa Delantera Central',
    widthCm: 26,
    heightCm: 11,
    areaCm2: 286,
    pricePerCm2: 25,
    totalPriceMxn: 50000,
    position3D: [0, 0.45, 1.95],
    rotation3D: [0, 0, 0],
    scale3D: [0.92, 0.39, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-28',
    expiryDate: '2028-08-28',
    viewsCount: 5100,
    clicksCount: 360,
    certificateId: 'P992-BODY-800008',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
  },
  {
    id: 'sp-front-2',
    brandName: 'Alpinestars Gear',
    sponsorName: 'Alpinestars Motorsports',
    slogan: 'One Goal. One Vision. FIA Race Suits',
    logoUrl: SPONSOR_LOGOS['sp-front-2'] || '',
    targetUrl: 'https://alpinestars.com',
    email: 'racing@alpinestars.com',
    tier: 'body_standard',
    zoneName: 'Defensa Delantera Izquierda',
    widthCm: 22,
    heightCm: 11,
    areaCm2: 242,
    pricePerCm2: 25,
    totalPriceMxn: 40000,
    position3D: [-0.55, 0.46, 1.82],
    rotation3D: [0, -0.35, 0],
    scale3D: [0.78, 0.39, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-28',
    expiryDate: '2028-08-28',
    viewsCount: 4500,
    clicksCount: 320,
    certificateId: 'P992-BODY-900009',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
  },
  {
    id: 'sp-front-3',
    brandName: 'OMP Racing Tech',
    sponsorName: 'OMP Racing Safety Equipment',
    slogan: 'Safety and Performance for GT Champions',
    logoUrl: SPONSOR_LOGOS['sp-front-3'] || '',
    targetUrl: 'https://ompracing.com',
    email: 'info@ompracing.it',
    tier: 'body_standard',
    zoneName: 'Defensa Delantera Derecha',
    widthCm: 22,
    heightCm: 11,
    areaCm2: 242,
    pricePerCm2: 25,
    totalPriceMxn: 40000,
    position3D: [0.55, 0.46, 1.82],
    rotation3D: [0, 0.35, 0],
    scale3D: [0.78, 0.39, 1],
    rotationAngle: 0,
    stickerBgColor: 'transparent',
    stickerBorderColor: 'transparent',
    logoScale: 1,
    contractYears: 2,
    createdAt: '2026-08-28',
    expiryDate: '2028-08-28',
    viewsCount: 4300,
    clicksCount: 300,
    certificateId: 'P992-BODY-100010',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
  },
];

// Set SOLD_OUT_SPONSORS as initial default demo data for instant testing
export const INITIAL_SPONSORS: Sponsor[] = SOLD_OUT_SPONSORS;
