import type { Sponsor, ZoneConfig, TrackEvent, SizeComparison } from '../types/sponsor';


export const CAMPAIGN_GOAL_MXN = 3000000; // $3,000,000 MXN
export const CONTRACT_YEARS = 2;
export const CONTRACT_DAYS = 730; // 365 * 2

export const ZONES: ZoneConfig[] = [
  {
    id: 'vip_wing',
    name: 'Alerón & Cajuela Trasera (VIP)',
    shortName: 'Alerón / Trasera',
    description: 'La zona trasera de máxima exposición en pista, tomas onboard y fotos de persecución.',
    pricePerCm2: 25,
    defaultPosition: [0, 0.82, -1.82],
    defaultRotation: [-1.67, 0, 0],
    defaultScale: [0.85, 0.25, 1],
    cameraPreset: {
      position: [0, 1.6, -3.2],
      target: [0, 0.7, -1.4],
    },
    highlightColor: '#fdd835',
    badgeText: 'MÁXIMO IMPACTO',
  },
  {
    id: 'hood_central',
    name: 'Cofre Aerodinámico Central',
    shortName: 'Cofre Central',
    description: 'Impacto frontal directo. Visible en todas las tomas frontales, videos y exhibiciones.',
    pricePerCm2: 20,
    defaultPosition: [0, 0.72, 1.25],
    defaultRotation: [-1.22, 0, 0],
    defaultScale: [0.70, 0.38, 1],
    cameraPreset: {
      position: [0, 1.6, 3.0],
      target: [0, 0.6, 1.0],
    },
    highlightColor: '#e00000',
    badgeText: 'FRONTAL ESTRELLA',
  },
  {
    id: 'premium_door',
    name: 'Puertas Laterales',
    shortName: 'Puertas Laterales',
    description: 'Gran formato lateral. El espacio clásico de los autos GT de competición para patrocinios principales.',
    pricePerCm2: 15,
    defaultPosition: [0.92, 0.62, 0.05],
    defaultRotation: [0, 1.57, 0],
    defaultScale: [0.75, 0.38, 1],
    cameraPreset: {
      position: [3.4, 1.0, 0.0],
      target: [0, 0.6, 0.0],
    },
    highlightColor: '#0070bb',
    badgeText: 'GRAN FORMATO',
  },
  {
    id: 'body_standard',
    name: 'Salpicaderas & Facias',
    shortName: 'Salpicaderas',
    description: 'Salpicaderas delanteras y traseras con visibilidad dinámica 360° en curvas.',
    pricePerCm2: 10,
    defaultPosition: [-0.88, 0.60, 1.15],
    defaultRotation: [-0.15, -1.45, 0],
    defaultScale: [0.50, 0.25, 1],
    cameraPreset: {
      position: [-2.6, 1.1, 1.8],
      target: [-0.4, 0.6, 0.6],
    },
    highlightColor: '#10b981',
    badgeText: 'ALTA VISIBILIDAD',
  },
  {
    id: 'showroom_floor',
    name: 'Podio Showroom Digital',
    shortName: 'Showroom Digital',
    description: 'Espacio publicitario en el entorno digital del showroom interactivo 3D.',
    pricePerCm2: 1,
    defaultPosition: [0, 0.02, 0],
    defaultRotation: [-1.57, 0, 0],
    defaultScale: [2.0, 3.5, 1],
    cameraPreset: {
      position: [3.6, 2.8, 3.6],
      target: [0, 0.5, 0],
    },
    highlightColor: '#8b5cf6',
    badgeText: 'ACCESIBLE 24/7',
  },
];


export const SIZE_COMPARISONS: SizeComparison[] = [
  {
    name: 'Micro Sticker (Tarjeta)',
    dimensions: '8.5 x 5.5 cm',
    cm2: 50,
    objectComparison: 'Tamaño Tarjeta de Crédito',
    dailyCostMxn: (50 * 10) / CONTRACT_DAYS, // ~$0.27 MXN/día
    totalMxn: 500,
    iconName: 'CreditCard',
  },
  {
    name: 'Badge Pro (Smartphone)',
    dimensions: '10 x 15 cm',
    cm2: 150,
    objectComparison: 'Tamaño iPhone Pro Max',
    dailyCostMxn: (150 * 15) / CONTRACT_DAYS, // ~$1.23 MXN/día
    totalMxn: 2250,
    iconName: 'Smartphone',
  },
  {
    name: 'Medium Banner (Tablet)',
    dimensions: '20 x 25 cm',
    cm2: 500,
    objectComparison: 'Tamaño iPad / Revista',
    dailyCostMxn: (500 * 15) / CONTRACT_DAYS, // ~$4.10 MXN/día
    totalMxn: 7500,
    iconName: 'Tablet',
  },
  {
    name: 'Mega Logo (Laptop)',
    dimensions: '35 x 30 cm',
    cm2: 1050,
    objectComparison: 'Tamaño Laptop 15" / Puerta',
    dailyCostMxn: (1050 * 20) / CONTRACT_DAYS, // ~$11.50 MXN/día
    totalMxn: 21000,
    iconName: 'Monitor',
  },
  {
    name: 'Title Sponsor (Trasera Completa)',
    dimensions: '140 x 25 cm',
    cm2: 3500,
    objectComparison: 'Envergadura total trasera del Porsche 911',
    dailyCostMxn: (3500 * 25) / CONTRACT_DAYS, // ~$47.94 MXN/día
    totalMxn: 87500,
    iconName: 'Trophy',
  },
];

export const TRACK_EVENTS_ROADMAP: TrackEvent[] = [
  {
    id: 'track-1',
    title: 'Gran Lanzamiento & Vinilado Oficial en Vivo',
    location: 'Porsche Center CDMX / Santa Fe',
    trackName: 'Exhibición Inaugural',
    date: 'Día 1 de Entrega',
    yearSpan: 'Año 1 - 2026',
    estimatedReach: '500,000+ Vistas digitales & 300 invitados VIP',
    type: 'Exhibición VIP',
    description: 'Sesión de rotulación en vivo de todos los patrocinadores, unboxing oficial del 911 (992) y cobertura por medios del motor.',
  },
  {
    id: 'track-2',
    title: 'Track Day Copa Porsche Hermanos Rodríguez',
    location: 'Ciudad de México',
    trackName: 'Autódromo Hermanos Rodríguez (F1 Track)',
    date: 'Temporada Track Days',
    yearSpan: 'Años 1 al 5 (Anual)',
    estimatedReach: '15,000 asistentes en paddock + 1.2M alcance en redes',
    type: 'Carrera Time Attack',
    description: 'Vueltas rápidas en el mítico circuito de Fórmula 1. Los logos en cofre, puertas y alerón serán el centro de atención.',
  },
  {
    id: 'track-3',
    title: 'Gira Nacional de Autódromos México',
    location: 'Monterrey, San Luis Potosí (Tangamanga), Guadalajara',
    trackName: 'Autódromo Monterrey & Parque Tangamanga II',
    date: 'Gira de Verano e Invierno',
    yearSpan: 'Años 1 al 5',
    estimatedReach: '45,000 aficionados presenciales + Cobertura nacional',
    type: 'Gira Nacional',
    description: 'Track Days regionales, sesiones de time attack y exhibición en pits con acceso a patrocinadores.',
  },
  {
    id: 'track-4',
    title: 'Cars & Coffee Luxury Meets & Expos de Superautos',
    location: 'Valle de Bravo, Cancún, Zapopan, San Pedro Garza García',
    trackName: 'Exclusivos Country Clubs & Plazas de Lujo',
    date: 'Mensual durante 2 años',
    yearSpan: '24 Eventos en 2 años',
    estimatedReach: 'Comunidad de alto poder adquisitivo y directores de empresas',
    type: 'Car Meet',
    description: 'Presencia continua en las reuniones de superdeportivos más exclusivas del país con material fotográfico profesional para las marcas.',
  },
];

export const INITIAL_SPONSORS: Sponsor[] = [
  {
    id: 'sp-001',
    brandName: 'Apex Racing Dynamics',
    slogan: 'Ingeniería en telemetría y software para motorsport de alto rendimiento.',
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
    targetUrl: 'https://apex-racing.example.com',
    email: 'contacto@apexracing.com',
    category: 'Motorsport & Tuning',
    tier: 'vip_wing',
    widthCm: 80,
    heightCm: 20,
    areaCm2: 1600,
    pricePerCm2: 25,
    totalPriceMxn: 40000,
    position3D: [0, 0.82, -1.82],
    rotation3D: [-1.67, 0, 0],
    scale3D: [0.85, 0.25, 1],
    zoneName: 'Alerón & Cajuela Trasera (VIP)',
    createdAt: '2026-08-20',
    contractYears: 2,
    expiryDate: '2028-08-20',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 4,
    viewsCount: 14200,
    clicksCount: 840,
    certificateId: 'P992-VIP-00189',
  },
  {
    id: 'sp-002',
    brandName: 'Quantum AI Cloud',
    slogan: 'Infraestructura de Inteligencia Artificial para fintech de ultra baja latencia.',
    logoUrl: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=200&auto=format&fit=crop&q=80',
    targetUrl: 'https://quantumcloud.example.com',
    email: 'hello@quantumcloud.ai',
    category: 'Tecnología & AI',
    tier: 'hood_central',
    widthCm: 50,
    heightCm: 30,
    areaCm2: 1500,
    pricePerCm2: 20,
    totalPriceMxn: 30000,
    position3D: [0, 0.72, 1.25],
    rotation3D: [-1.22, 0, 0],
    scale3D: [0.70, 0.38, 1],
    zoneName: 'Cofre Aerodinámico Central',
    createdAt: '2026-08-22',
    contractYears: 2,
    expiryDate: '2028-08-22',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 3,
    viewsCount: 18900,
    clicksCount: 1220,
    certificateId: 'P992-HOOD-00244',
  },
  {
    id: 'sp-003',
    brandName: 'Veloce Capital Fund',
    slogan: 'Fondo de inversión de riesgo en tecnologías disruptivas de Latinoamérica.',
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
    targetUrl: 'https://velocecapital.example.com',
    email: 'partners@velocecap.com',
    category: 'Finanzas & Cripto',
    tier: 'premium_door',
    widthCm: 60,
    heightCm: 30,
    areaCm2: 1800,
    pricePerCm2: 15,
    totalPriceMxn: 27000,
    position3D: [0.92, 0.62, 0.05],
    rotation3D: [0, 1.57, 0],
    scale3D: [0.75, 0.38, 1],
    zoneName: 'Puerta Lateral Derecha',
    createdAt: '2026-08-24',
    contractYears: 2,
    expiryDate: '2028-08-24',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
    viewsCount: 9500,
    clicksCount: 512,
    certificateId: 'P992-DOOR-00311',
  },
  {
    id: 'sp-004',
    brandName: 'NitroEnergy Drink',
    slogan: 'Bebida energética para pilotos y atletas de alto rendimiento.',
    logoUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=200&auto=format&fit=crop&q=80',
    targetUrl: 'https://nitroenergy.example.com',
    email: 'promo@nitroenergy.com',
    category: 'Gastronomía & Bebidas',
    tier: 'premium_door',
    widthCm: 60,
    heightCm: 30,
    areaCm2: 1800,
    pricePerCm2: 15,
    totalPriceMxn: 27000,
    position3D: [-0.92, 0.62, 0.05],
    rotation3D: [0, -1.57, 0],
    scale3D: [0.75, 0.38, 1],
    zoneName: 'Puerta Lateral Izquierda',
    createdAt: '2026-08-25',
    contractYears: 2,
    expiryDate: '2028-08-25',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 2,
    viewsCount: 11300,
    clicksCount: 680,
    certificateId: 'P992-DOOR-00312',
  },
  {
    id: 'sp-005',
    brandName: 'CarbonForge Optics',
    slogan: 'Gafas polarizadas de fibra de carbono ultra liviana para conducción.',
    logoUrl: 'https://images.unsplash.com/photo-1508296695146-257a814070b4?w=200&auto=format&fit=crop&q=80',
    targetUrl: 'https://carbonforge.example.com',
    email: 'info@carbonforge.mx',
    category: 'Moda & Lujo',
    tier: 'body_standard',
    widthCm: 30,
    heightCm: 15,
    areaCm2: 450,
    pricePerCm2: 10,
    totalPriceMxn: 4500,
    position3D: [0.88, 0.60, 1.15],
    rotation3D: [-0.15, 1.45, 0],
    scale3D: [0.50, 0.25, 1],
    zoneName: 'Salpicadera Delantera Derecha',
    createdAt: '2026-08-26',
    contractYears: 2,
    expiryDate: '2028-08-26',
    includesPhysicalVinylWrap: true,
    includesTrackDaysExhibition: true,
    includesSocialMediaTags: true,
    vipTrackPassesCount: 1,
    viewsCount: 4200,
    clicksCount: 290,
    certificateId: 'P992-BODY-00508',
  },
];

